# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC5304():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC5304(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.LINK_TEXT, "Your profile").click()
    self.driver.find_element(By.LINK_TEXT, "Edit Profile").click()
    previous_phone_number = self.driver.find_element(By.NAME, "phone").get_attribute('value')
    self.driver.find_element(By.NAME, "phone").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(10)").click()
    self.driver.find_element(By.NAME, "phone").send_keys("1159842654")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(11)").click()
    self.driver.find_element(By.LINK_TEXT, "Your profile").click()
    self.driver.find_element(By.LINK_TEXT, "Edit Profile").click()
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
    new_phone_number = self.driver.find_element(By.NAME, "phone").get_attribute('value')
    assert previous_phone_number != new_phone_number

  
