# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC1603():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC1603(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.LINK_TEXT, "Register here").click()
    register_url = self.driver.current_url
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("lean31@gmail.com")
    self.driver.find_element(By.ID, "password").send_keys("dasd123")
    self.driver.find_element(By.ID, "cpassword").send_keys("dasd123")
    self.driver.find_element(By.NAME, "lastName").send_keys("Rodriguez")
    self.driver.find_element(By.NAME, "address1").send_keys("Lima 231")
    self.driver.find_element(By.NAME, "address2").send_keys("Entre Independendicia y Chile")
    self.driver.find_element(By.NAME, "zipcode").send_keys("6435")
    self.driver.find_element(By.NAME, "city").send_keys("Miami")
    self.driver.find_element(By.NAME, "state").send_keys("Florida")
    self.driver.find_element(By.NAME, "country").send_keys("USA")
    self.driver.find_element(By.NAME, "phone").send_keys("1126547843")
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").click()
    element = self.driver.find_element(By.NAME, "email")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(8)").click()
    self.driver.find_element(By.CSS_SELECTOR, "form").click()
    self.driver.find_element(By.CSS_SELECTOR, "form").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(13) > input").click()
    #assert self.driver.current_url == "http://127.0.0.1:5000/register" pass
    assert self.driver.current_url == register_url
  
